server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: api-cert
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:123456}

spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/Ecommerce
      client:
        registration:
          keycloak:
            client-id: backend-client
            client-secret: ${KEYCLOAK_BACKEND_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/Ecommerce

keycloak:
  auth-server-url: http://keycloak:8080
  realm: Ecommerce
  resource: backend-client
  credentials:
    secret: ${KEYCLOAK_BACKEND_CLIENT_SECRET}
  ssl-required: none

logging:
  level:
    org.keycloak: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.patrones.api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
