server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: api-cert
    key-store-password: 123456

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak:8443/realms/parcial-realm
      client:
        registration:
          keycloak:
            client-id: backend-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET:default-secret-change-me}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: https://keycloak:8443/realms/parcial-realm

keycloak:
  auth-server-url: https://keycloak:8443
  realm: parcial-realm
  resource: backend-client
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:default-secret-change-me}

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    com.patrones.api: DEBUG
